Insert spaces between words starting with capital letters
giangle-unikie/Python pull request #2
Opened 2023-02-17 11:33 UTC by giangle-unikie

This program will insert spaces between words starting with capital letters

2023-02-17 11:58 UTC, millavalio-Unikie requested changes
Otherwise the program works without problems, but giving an empty string as an input causes the program to crash.

2023-02-20 10:46 UTC, millavalio-Unikie approved these changes

2023-02-21 10:35 UTC, millavalio-Unikie approved these changes
Approving again after accidental re-review request.

2023-02-21 11:32 UTC, jourau commented
$ python3 insert_spaces.py 
Enter a string: HELLO World         
H E L L O  World

I was thinking that space should be inserted between words starting with capital letter not between capital letters in the  word itself. README.md with examples would be nice to have.

2023-02-21 11:53 UTC, jounraun approved these changes

2023-02-21 11:53 UTC, jounraun approved these changes

2023-02-21 11:54 UTC, jourau approved these changes

2023-02-21 11:54 UTC, merged