[QA - 1315] Create test file for program insert spaces and bash scripts
giangle-unikie/Python pull request #4
Opened 2023-03-07 14:19 UTC by giangle-unikie

Add bash scripts and the tests for the insert_spaces program

2023-03-08 06:40 UTC, millavalio-Unikie requested changes

2023-03-08 06:40 UTC, millavalio-Unikie commented on build_and_test.sh
> +pytest --junitxml=test-report.xml
Coverage generation is missing.

2023-03-08 12:12 UTC, millavalio-Unikie approved these changes

2023-03-09 11:04 UTC, jourau approved these changes

2023-03-10 13:04 UTC, merged